# Efficient LLM Inference on A100 GPU with Python Triton

This notebook adapts the concepts from [Efficient-LLM-Inferencing-on-GPUs](https://github.com/yinuotxie/Efficient-LLM-Inferencing-on-GPUs) (originally in CUDA C++) into **Python Triton kernels** optimized for **NVIDIA A100 GPUs**.

## What We'll Implement

| Component | What It Does | Why It's Faster |
|---|---|---|
| **Naive Attention** | Baseline `softmax(QK^T)V` | Reference implementation |
| **Flash Attention** | Tiled, IO-aware attention | Minimizes HBM reads/writes via SRAM tiling |
| **Flash Decoding** | Decode-phase optimized attention | Parallelizes over KV sequence length |
| **Paged KV Cache** | OS-style virtual memory for KV cache | Reduces memory fragmentation |
| **vLLM Integration** | End-to-end LLM serving (Mistral-7B) | Combines all optimizations |

## A100 GPU Specs & Memory Hierarchy

```
NVIDIA A100 (sm_80) - 108 Streaming Multiprocessors
+---------------------------------------------------------+
|  Tensor Cores (3rd gen)     |  312 TFLOPS FP16/BF16    |
|                             |  19.5 TFLOPS FP32        |
+---------------------------------------------------------+
|  GPU SRAM (on-chip)         |  ~40 MB   |  ~19 TB/s    |
|  (192 KB shared mem / SM)   |           |  FAST         |
+---------------------------------------------------------+
|  L2 Cache                   |  40 MB    |  ~6 TB/s     |
+---------------------------------------------------------+
|  GPU HBM2e (off-chip)       |  40/80 GB |  ~2 TB/s     |
|  (global memory / VRAM)     |           |  SLOW (10x)   |
+---------------------------------------------------------+
```

A100 has **2x SRAM** (192KB/SM vs 96KB) and **2x HBM bandwidth** vs T4/L4.  
Our Triton kernels exploit this with **larger tile sizes** and **more parallelism**.

## 1. Setup & Installation

In [ ]:
# Install dependencies
!pip install -q triton torch vllm

import torch
import triton
import triton.language as tl
import math
import time

# Verify A100 GPU
assert torch.cuda.is_available(), "GPU not found! Go to Runtime > Change runtime type > A100"
gpu_name = torch.cuda.get_device_name(0)
gpu_mem = torch.cuda.get_device_properties(0).total_memory / 1e9
gpu_props = torch.cuda.get_device_properties(0)

print(f"GPU: {gpu_name}")
print(f"VRAM: {gpu_mem:.1f} GB")
print(f"SMs: {gpu_props.multi_processor_count}")
print(f"Compute Capability: {gpu_props.major}.{gpu_props.minor}")
print(f"Triton: {triton.__version__}")
print(f"PyTorch: {torch.__version__}")

if 'A100' in gpu_name:
    print("\nA100 detected — using optimized configs (BLOCK=128, BF16, large seqs)")
elif 'H100' in gpu_name:
    print("\nH100 detected — even better! Same configs will work.")
else:
    print(f"\nWARNING: Expected A100, got {gpu_name}. Kernels will still work but block sizes are tuned for A100.")

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 44.0/44.0 kB 4.7 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 87.9/87.9 kB 11.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 433.2/433.2 MB 5.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 192.6/192.6 kB 19.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 45.5/45.5 kB 5.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.8/7.8 MB 152.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 111.0/111.0 kB 9.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 45.4/45.4 kB 3.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.9/3.9 MB 123.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.3/2.3 MB 105.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 469.4/469.4 kB 40.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 114.2/114.2 kB 13.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.

## 2. Naive Attention (Baseline)

Standard attention: `O = softmax(QK^T / sqrt(d)) @ V`

This materializes the **full NxN attention matrix** in HBM:

```
Q (N, d)  @  K^T (d, N)  ->  S (N, N)  ->  softmax  ->  P (N, N)  @  V (N, d)  ->  O (N, d)
              ^                  ^                        ^
         HBM read          HBM write (O(N^2))         HBM read again
```

On A100 with seq_len=8192: the NxN matrix = **512 MB per head** in FP16!

In [ ]:
def naive_attention(Q, K, V):
    """Standard attention — materializes full NxN matrix in HBM."""
    d = Q.shape[-1]
    scores = torch.matmul(Q, K.transpose(-2, -1)) / math.sqrt(d)
    attn_weights = torch.softmax(scores, dim=-1)
    output = torch.matmul(attn_weights, V)
    return output


# A100 can handle bigger tensors
B, H, N, d = 4, 32, 1024, 128
Q = torch.randn(B, H, N, d, device='cuda', dtype=torch.bfloat16)
K = torch.randn(B, H, N, d, device='cuda', dtype=torch.bfloat16)
V = torch.randn(B, H, N, d, device='cuda', dtype=torch.bfloat16)

naive_out = naive_attention(Q, K, V)
print(f"Naive attention output shape: {naive_out.shape}")
print(f"Memory for NxN attention matrix: {B * H * N * N * 2 / 1e6:.1f} MB (bf16)")
print(f"A100 can hold this in HBM, but the bandwidth cost is the bottleneck!")

Naive attention output shape: torch.Size([4, 32, 1024, 128])
Memory for NxN attention matrix: 268.4 MB (bf16)
A100 can hold this in HBM, but the bandwidth cost is the bottleneck!


## 3. Flash Attention in Triton (A100 Optimized)

### Core Idea
Instead of materializing the full NxN attention matrix, process it in **tiles** that fit in SRAM:

```
For each block of Q (BLOCK_M=128 rows):     <- larger tiles on A100!
    Load Q_block into SRAM (192KB available per SM)
    Initialize: output = 0, running_max = -inf, running_sum = 0
    
    For each block of K,V (BLOCK_N=128 cols):
        Load K_block, V_block into SRAM
        Compute scores = Q_block @ K_block^T     <- uses Tensor Cores!
        Update running softmax (online algorithm)
        Accumulate output += attn_weights @ V_block
    
    Write final output block to HBM
```

### A100 Advantages for Flash Attention
- **192 KB shared memory per SM** -> larger BLOCK_M/BLOCK_N (128 vs 64 on T4)
- **108 SMs** -> more blocks can run in parallel
- **3rd gen Tensor Cores** -> `tl.dot()` maps directly to fast matrix multiply
- **BF16 support** -> better numerical range than FP16, same speed

In [ ]:
@triton.autotune(
    configs=[
        triton.Config({'BLOCK_M': 128, 'BLOCK_N': 128}, num_warps=8, num_stages=3),
        triton.Config({'BLOCK_M': 128, 'BLOCK_N': 64}, num_warps=4, num_stages=4),
        triton.Config({'BLOCK_M': 64, 'BLOCK_N': 128}, num_warps=8, num_stages=3),
        triton.Config({'BLOCK_M': 64, 'BLOCK_N': 64}, num_warps=4, num_stages=2),
    ],
    key=['N_CTX'],
)
@triton.jit
def _flash_attn_fwd_kernel(
    Q_ptr, K_ptr, V_ptr, O_ptr,
    stride_qb, stride_qh, stride_qm, stride_qk,
    stride_kb, stride_kh, stride_kn, stride_kk,
    stride_vb, stride_vh, stride_vn, stride_vk,
    stride_ob, stride_oh, stride_om, stride_ok,
    NUM_HEADS,
    N_CTX: tl.constexpr,
    HEAD_DIM: tl.constexpr,
    BLOCK_M: tl.constexpr,
    BLOCK_N: tl.constexpr,
):
    """Flash Attention forward pass — A100 optimized.

    Each program instance handles one (batch, head, q_block) tile.
    Larger BLOCK sizes exploit A100's 192KB shared memory per SM.
    """
    pid_m = tl.program_id(0)
    pid_bh = tl.program_id(1)

    batch_idx = pid_bh // NUM_HEADS
    head_idx = pid_bh % NUM_HEADS

    q_base = Q_ptr + batch_idx * stride_qb + head_idx * stride_qh
    k_base = K_ptr + batch_idx * stride_kb + head_idx * stride_kh
    v_base = V_ptr + batch_idx * stride_vb + head_idx * stride_vh
    o_base = O_ptr + batch_idx * stride_ob + head_idx * stride_oh

    offs_m = pid_m * BLOCK_M + tl.arange(0, BLOCK_M)
    offs_k = tl.arange(0, HEAD_DIM)
    offs_n = tl.arange(0, BLOCK_N)

    # Load Q block into SRAM
    q_ptrs = q_base + offs_m[:, None] * stride_qm + offs_k[None, :] * stride_qk
    q_mask = offs_m[:, None] < N_CTX
    q = tl.load(q_ptrs, mask=q_mask, other=0.0)

    # Scale factor — use Python float, not .to() on constexpr
    sm_scale: tl.constexpr = 1.0 / (HEAD_DIM ** 0.5)

    # Online softmax accumulators (FP32 for numerical stability)
    m_i = tl.full([BLOCK_M], float('-inf'), dtype=tl.float32)
    l_i = tl.zeros([BLOCK_M], dtype=tl.float32)
    acc = tl.zeros([BLOCK_M, HEAD_DIM], dtype=tl.float32)

    # Iterate over K/V blocks (each fits in A100 SRAM)
    for start_n in range(0, N_CTX, BLOCK_N):
        cur_n = start_n + offs_n

        # Load K block
        k_ptrs = k_base + cur_n[:, None] * stride_kn + offs_k[None, :] * stride_kk
        k_mask = cur_n[:, None] < N_CTX
        k = tl.load(k_ptrs, mask=k_mask, other=0.0)

        # QK^T via tl.dot -> maps to A100 Tensor Cores
        scores = tl.dot(q, tl.trans(k)) * sm_scale
        scores = tl.where(cur_n[None, :] < N_CTX, scores, float('-inf'))

        # Online softmax update
        m_ij = tl.max(scores, axis=1)
        m_new = tl.maximum(m_i, m_ij)
        alpha = tl.exp(m_i - m_new)
        l_i = l_i * alpha
        acc = acc * alpha[:, None]

        p = tl.exp(scores - m_new[:, None])
        l_i += tl.sum(p, axis=1)

        # Load V and accumulate via Tensor Core dot
        v_ptrs = v_base + cur_n[:, None] * stride_vn + offs_k[None, :] * stride_vk
        v_mask = cur_n[:, None] < N_CTX
        v = tl.load(v_ptrs, mask=v_mask, other=0.0)
        acc += tl.dot(p.to(v.dtype), v).to(tl.float32)

        m_i = m_new

    # Normalize and write to HBM
    acc = acc / l_i[:, None]
    o_ptrs = o_base + offs_m[:, None] * stride_om + offs_k[None, :] * stride_ok
    o_mask = offs_m[:, None] < N_CTX
    tl.store(o_ptrs, acc.to(tl.bfloat16), mask=o_mask)

In [ ]:
def flash_attention_triton(Q, K, V):
    """Flash Attention wrapper — A100 optimized tile sizes."""
    B, H, N, d = Q.shape
    O = torch.empty_like(Q)

    # A100 optimal tile sizes (2x larger than T4 due to 192KB SRAM/SM)
    grid = lambda meta: (triton.cdiv(N, meta['BLOCK_M']), B * H)

    _flash_attn_fwd_kernel[grid](
        Q, K, V, O,
        Q.stride(0), Q.stride(1), Q.stride(2), Q.stride(3),
        K.stride(0), K.stride(1), K.stride(2), K.stride(3),
        V.stride(0), V.stride(1), V.stride(2), V.stride(3),
        O.stride(0), O.stride(1), O.stride(2), O.stride(3),
        H,  # NUM_HEADS
        N_CTX=N,
        HEAD_DIM=d,
    )
    return O


# Correctness test
flash_out = flash_attention_triton(Q, K, V)
max_diff = (flash_out.float() - naive_out.float()).abs().max().item()
print(f"Flash Attention output shape: {flash_out.shape}")
print(f"Max diff vs naive: {max_diff:.6f}")
print(f"Correct: {max_diff < 1e-2}")
print(f"\nA100 config: BLOCK_M=128, BLOCK_N=128, HEAD_DIM={d}, dtype=BF16")

Flash Attention output shape: torch.Size([4, 32, 1024, 128])
Max diff vs naive: 0.007812
Correct: True

A100 config: BLOCK_M=128, BLOCK_N=128, HEAD_DIM=128, dtype=BF16


## 4. Flash Decoding in Triton (A100 Optimized)

### The Problem
During decode (token generation), `q_len=1`. FlashAttention parallelizes over q_blocks:
```
Parallelism = batch x heads x q_blocks = B x H x 1
A100 has 108 SMs... with B=1, H=32: only 32 blocks = 30% utilization!
```

### Flash Decoding on A100
Add KV-split parallelism to **saturate all 108 SMs**:
```
Parallelism = batch x heads x kv_splits
With B=1, H=32, splits=16: 512 blocks -> 108 SMs fully busy!
```

A100 benefits: more splits since we have more SMs and SRAM to handle them.

In [ ]:
@triton.jit
def _flash_decoding_stage1_kernel(
    Q_ptr, K_ptr, V_ptr,
    Partial_O_ptr,
    Partial_lse_ptr,
    stride_qb, stride_qh, stride_qd,
    stride_kb, stride_kh, stride_kn, stride_kd,
    stride_vb, stride_vh, stride_vn, stride_vd,
    stride_pob, stride_poh, stride_pos, stride_pod,
    stride_plb, stride_plh, stride_pls,
    NUM_HEADS,
    SEQ_LEN: tl.constexpr,
    HEAD_DIM: tl.constexpr,
    BLOCK_N: tl.constexpr,
    NUM_SPLITS: tl.constexpr,
):
    """Stage 1: Each program handles one (batch, head, kv_split).
    Larger BLOCK_N on A100 means fewer iterations per split.
    """
    pid_split = tl.program_id(0)
    pid_bh = tl.program_id(1)

    batch_idx = pid_bh // NUM_HEADS
    head_idx = pid_bh % NUM_HEADS

    split_size = tl.cdiv(SEQ_LEN, NUM_SPLITS)
    start_n = pid_split * split_size
    end_n = tl.minimum(start_n + split_size, SEQ_LEN)

    offs_d = tl.arange(0, HEAD_DIM)
    q_ptrs = Q_ptr + batch_idx * stride_qb + head_idx * stride_qh + offs_d * stride_qd
    q = tl.load(q_ptrs)

    sm_scale: tl.constexpr = 1.0 / (HEAD_DIM ** 0.5)

    m_i = float('-inf')
    l_i = 0.0
    acc = tl.zeros([HEAD_DIM], dtype=tl.float32)

    for block_start in range(start_n, end_n, BLOCK_N):
        offs_n = block_start + tl.arange(0, BLOCK_N)
        n_mask = offs_n < end_n

        k_ptrs = (K_ptr + batch_idx * stride_kb + head_idx * stride_kh
                  + offs_n[:, None] * stride_kn + offs_d[None, :] * stride_kd)
        k = tl.load(k_ptrs, mask=n_mask[:, None], other=0.0)

        scores = tl.sum(q[None, :] * k, axis=1) * sm_scale
        scores = tl.where(n_mask, scores, float('-inf'))

        m_ij = tl.max(scores, axis=0)
        m_new = tl.maximum(m_i, m_ij)
        alpha = tl.exp(m_i - m_new)
        l_i = l_i * alpha
        acc = acc * alpha

        p = tl.exp(scores - m_new)
        l_i += tl.sum(p, axis=0)

        v_ptrs = (V_ptr + batch_idx * stride_vb + head_idx * stride_vh
                  + offs_n[:, None] * stride_vn + offs_d[None, :] * stride_vd)
        v = tl.load(v_ptrs, mask=n_mask[:, None], other=0.0)
        acc += tl.sum(p[:, None] * v.to(tl.float32), axis=0)

        m_i = m_new

    # Normalize before storing — Stage 2 expects normalized partial outputs
    acc = acc / l_i
    po_ptrs = (Partial_O_ptr + batch_idx * stride_pob + head_idx * stride_poh
               + pid_split * stride_pos + offs_d * stride_pod)
    tl.store(po_ptrs, acc.to(tl.bfloat16))

    lse = tl.log(l_i) + m_i
    lse_ptr = (Partial_lse_ptr + batch_idx * stride_plb + head_idx * stride_plh
               + pid_split * stride_pls)
    tl.store(lse_ptr, lse)

In [ ]:
@triton.jit
def _flash_decoding_stage2_kernel(
    Partial_O_ptr, Partial_lse_ptr, O_ptr,
    stride_pob, stride_poh, stride_pos, stride_pod,
    stride_plb, stride_plh, stride_pls,
    stride_ob, stride_oh, stride_od,
    NUM_HEADS,
    HEAD_DIM: tl.constexpr,
    NUM_SPLITS: tl.constexpr,
):
    """Stage 2: Reduce partial outputs across splits using log-sum-exp."""
    pid_bh = tl.program_id(0)

    batch_idx = pid_bh // NUM_HEADS
    head_idx = pid_bh % NUM_HEADS

    offs_d = tl.arange(0, HEAD_DIM)
    offs_s = tl.arange(0, NUM_SPLITS)

    lse_ptrs = (Partial_lse_ptr + batch_idx * stride_plb
                + head_idx * stride_plh + offs_s * stride_pls)
    lse = tl.load(lse_ptrs)

    global_max = tl.max(lse, axis=0)
    weights = tl.exp(lse - global_max)
    total_weight = tl.sum(weights, axis=0)

    acc = tl.zeros([HEAD_DIM], dtype=tl.float32)
    for s in range(NUM_SPLITS):
        po_ptrs = (Partial_O_ptr + batch_idx * stride_pob
                   + head_idx * stride_poh + s * stride_pos + offs_d * stride_pod)
        partial_o = tl.load(po_ptrs).to(tl.float32)

        lse_s_ptr = (Partial_lse_ptr + batch_idx * stride_plb
                     + head_idx * stride_plh + s * stride_pls)
        lse_s = tl.load(lse_s_ptr)
        w = tl.exp(lse_s - global_max)
        acc += w * partial_o

    acc = acc / total_weight

    o_ptrs = (O_ptr + batch_idx * stride_ob + head_idx * stride_oh
              + offs_d * stride_od)
    tl.store(o_ptrs, acc.to(tl.bfloat16))

In [ ]:
def flash_decoding_triton(Q, K, V, num_splits=16):
    """Flash Decoding — A100 optimized (q_len=1, larger splits).

    A100: 16 splits x 32 heads = 512 thread blocks -> 108 SMs saturated
    """
    B, H, _, d = Q.shape
    N = K.shape[2]

    Q_squeezed = Q.squeeze(2).contiguous()

    partial_O = torch.empty(B, H, num_splits, d, device='cuda', dtype=torch.bfloat16)
    partial_lse = torch.empty(B, H, num_splits, device='cuda', dtype=torch.float32)

    BLOCK_N = 128  # A100: larger blocks

    grid1 = (num_splits, B * H)
    _flash_decoding_stage1_kernel[grid1](
        Q_squeezed, K, V,
        partial_O, partial_lse,
        Q_squeezed.stride(0), Q_squeezed.stride(1), Q_squeezed.stride(2),
        K.stride(0), K.stride(1), K.stride(2), K.stride(3),
        V.stride(0), V.stride(1), V.stride(2), V.stride(3),
        partial_O.stride(0), partial_O.stride(1), partial_O.stride(2), partial_O.stride(3),
        partial_lse.stride(0), partial_lse.stride(1), partial_lse.stride(2),
        H,  # NUM_HEADS
        SEQ_LEN=N,
        HEAD_DIM=d,
        BLOCK_N=BLOCK_N,
        NUM_SPLITS=num_splits,
    )

    O = torch.empty(B, H, d, device='cuda', dtype=torch.bfloat16)
    grid2 = (B * H,)
    _flash_decoding_stage2_kernel[grid2](
        partial_O, partial_lse, O,
        partial_O.stride(0), partial_O.stride(1), partial_O.stride(2), partial_O.stride(3),
        partial_lse.stride(0), partial_lse.stride(1), partial_lse.stride(2),
        O.stride(0), O.stride(1), O.stride(2),
        H,  # NUM_HEADS
        HEAD_DIM=d,
        NUM_SPLITS=num_splits,
    )

    return O.unsqueeze(2)


# Correctness test with A100-scale dimensions
B, H, N, d = 4, 32, 4096, 128  # Mistral-7B like config
Q_dec = torch.randn(B, H, 1, d, device='cuda', dtype=torch.bfloat16)
K_dec = torch.randn(B, H, N, d, device='cuda', dtype=torch.bfloat16)
V_dec = torch.randn(B, H, N, d, device='cuda', dtype=torch.bfloat16)

ref_out = naive_attention(Q_dec, K_dec, V_dec)
fd_out = flash_decoding_triton(Q_dec, K_dec, V_dec, num_splits=16)

max_diff = (fd_out.float() - ref_out.float()).abs().max().item()
print(f"Flash Decoding output shape: {fd_out.shape}")
print(f"Max diff vs naive: {max_diff:.6f}")
print(f"Correct: {max_diff < 1e-1}")
print(f"\nA100 config: num_splits=16, BLOCK_N=128, {B*H*16} total thread blocks for 108 SMs")

Flash Decoding output shape: torch.Size([4, 32, 1, 128])
Max diff vs naive: 0.001343
Correct: True

A100 config: num_splits=16, BLOCK_N=128, 2048 total thread blocks for 108 SMs


## 5. Paged KV Cache (Concept Demo)

### The Problem
Traditional KV caches allocate **contiguous memory** per sequence:
```
A100 80GB with Mistral-7B (32 heads, d=128, FP16):
KV cache per token = 2 x 32 x 128 x 2 bytes = 16 KB
For max_seq=32768:  16KB x 32768 = 512 MB per sequence!
With batch=16:      512MB x 16 = 8 GB reserved (even if sequences are short)
```

### PagedAttention Solution
Allocate in small blocks (like OS pages) — only use what you need.

In [ ]:
class PagedKVCache:
    """Paged KV Cache — A100 sized (larger block pool)."""

    def __init__(self, num_blocks, block_size, num_heads, head_dim, dtype=torch.bfloat16):
        self.block_size = block_size
        self.num_blocks = num_blocks

        # Pre-allocated physical block pool on A100 HBM
        self.k_cache = torch.zeros(
            num_blocks, block_size, num_heads, head_dim,
            device='cuda', dtype=dtype
        )
        self.v_cache = torch.zeros(
            num_blocks, block_size, num_heads, head_dim,
            device='cuda', dtype=dtype
        )

        self.free_blocks = list(range(num_blocks))
        self.page_tables = {}

        mem_used = 2 * num_blocks * block_size * num_heads * head_dim * 2 / 1e9
        print(f"KV Cache pool: {num_blocks} blocks x {block_size} tokens")
        print(f"GPU memory reserved: {mem_used:.2f} GB")

    def allocate(self, seq_id, num_tokens):
        num_needed = math.ceil(num_tokens / self.block_size)
        if num_needed > len(self.free_blocks):
            raise RuntimeError(f"OOM: need {num_needed} blocks, only {len(self.free_blocks)} free")
        blocks = [self.free_blocks.pop(0) for _ in range(num_needed)]
        self.page_tables[seq_id] = blocks
        return blocks

    def free(self, seq_id):
        if seq_id in self.page_tables:
            self.free_blocks.extend(self.page_tables.pop(seq_id))

    def utilization(self):
        used = self.num_blocks - len(self.free_blocks)
        return f"{used}/{self.num_blocks} blocks ({100*used/self.num_blocks:.0f}%)"


# A100-scale demo: 256 blocks, Mistral-7B dimensions
cache = cache = PagedKVCache(num_blocks=1024, block_size=16, num_heads=32, head_dim=128)
print(f"\nInitial: {cache.utilization()}")

# Simulate concurrent requests with varying lengths
requests = [
    (0, 500),   # short prompt
    (1, 2048),  # medium context
    (2, 8192),  # long context (A100 can handle this)
    (3, 128),   # tiny request
]
for seq_id, num_tokens in requests:
    blocks = cache.allocate(seq_id, num_tokens)
    print(f"  Seq {seq_id}: {num_tokens} tokens -> {len(blocks)} blocks")

print(f"After allocations: {cache.utilization()}")

# Free completed requests, allocate new ones
cache.free(0)
cache.free(3)
cache.allocate(4, 4096)  # reuses freed blocks
print(f"After recycling: {cache.utilization()}")

# Show fragmentation resistance
print(f"\nPage tables (logical -> physical blocks):")
for seq_id, blocks in cache.page_tables.items():
    print(f"  Seq {seq_id}: {blocks[:5]}{'...' if len(blocks) > 5 else ''}")
print("Notice: blocks are non-contiguous — zero external fragmentation!")

KV Cache pool: 1024 blocks x 16 tokens
GPU memory reserved: 0.27 GB

Initial: 0/1024 blocks (0%)
  Seq 0: 500 tokens -> 32 blocks
  Seq 1: 2048 tokens -> 128 blocks
  Seq 2: 8192 tokens -> 512 blocks
  Seq 3: 128 tokens -> 8 blocks
After allocations: 680/1024 blocks (66%)
After recycling: 896/1024 blocks (88%)

Page tables (logical -> physical blocks):
  Seq 1: [32, 33, 34, 35, 36]...
  Seq 2: [160, 161, 162, 163, 164]...
  Seq 4: [680, 681, 682, 683, 684]...
Notice: blocks are non-contiguous — zero external fragmentation!


## 6. Benchmarks (A100 Scale)

Testing with larger dimensions that showcase A100's advantage:
- Sequences up to **16384** (A100 has enough HBM)
- 32 attention heads, head_dim=128 (Mistral/Llama config)
- BF16 precision (A100 native)

In [ ]:
def benchmark_fn(fn, *args, warmup=10, repeat=50):
    """Benchmark with CUDA sync."""
    for _ in range(warmup):
        fn(*args)
    torch.cuda.synchronize()
    start = time.perf_counter()
    for _ in range(repeat):
        fn(*args)
    torch.cuda.synchronize()
    elapsed = (time.perf_counter() - start) / repeat
    return elapsed * 1000  # ms


print("=" * 75)
print("FLASH ATTENTION BENCHMARK (Prefill Phase)")
print(f"Config: B=2, H=32, d=128, dtype=BF16, BLOCK_M=128, BLOCK_N=128")
print("=" * 75)
print(f"{'Seq Len':>8} | {'Naive (ms)':>12} | {'Flash Attn (ms)':>15} | {'Speedup':>8} | {'NxN Mem':>10}")
print("-" * 75)

B, H, d = 2, 32, 128
for N in [512, 1024, 2048, 4096, 8192, 16384]:
    Q = torch.randn(B, H, N, d, device='cuda', dtype=torch.bfloat16)
    K = torch.randn(B, H, N, d, device='cuda', dtype=torch.bfloat16)
    V = torch.randn(B, H, N, d, device='cuda', dtype=torch.bfloat16)

    nxn_mem = B * H * N * N * 2 / 1e6  # MB

    try:
        t_naive = benchmark_fn(naive_attention, Q, K, V)
        t_flash = benchmark_fn(flash_attention_triton, Q, K, V)
        speedup = t_naive / t_flash
        print(f"{N:>8} | {t_naive:>12.3f} | {t_flash:>15.3f} | {speedup:>7.2f}x | {nxn_mem:>8.0f} MB")
    except RuntimeError as e:
        print(f"{N:>8} | OOM or error: {str(e)[:50]}")
    finally:
        del Q, K, V
        torch.cuda.empty_cache()

print("=" * 75)
print("Note: Speedup grows with seq len because naive attention's O(N^2) HBM traffic dominates")

FLASH ATTENTION BENCHMARK (Prefill Phase)
Config: B=2, H=32, d=128, dtype=BF16, BLOCK_M=128, BLOCK_N=128
 Seq Len |   Naive (ms) | Flash Attn (ms) |  Speedup |    NxN Mem
---------------------------------------------------------------------------
     512 |        0.194 |           0.077 |    2.51x |       34 MB
    1024 |        0.671 |           0.214 |    3.13x |      134 MB
    2048 |        2.657 |           0.773 |    3.44x |      537 MB
    4096 |       12.369 |           2.919 |    4.24x |     2147 MB
    8192 |       53.276 |          11.456 |    4.65x |     8590 MB
   16384 |      153.016 |          45.905 |    3.33x |    34360 MB
Note: Speedup grows with seq len because naive attention's O(N^2) HBM traffic dominates


In [ ]:
# Free vLLM model to reclaim VRAM for benchmarking
try:
    del llm
    del stress_outputs
    del outputs
except NameError:
    pass
import gc
gc.collect()
torch.cuda.empty_cache()
print(f"VRAM free: {(torch.cuda.get_device_properties(0).total_memory - torch.cuda.memory_allocated()) / 1e9:.1f} GB")

VRAM free: 84.5 GB


In [ ]:
print("\n" + "=" * 75)
print("FLASH DECODING BENCHMARK (Decode Phase, q_len=1)")
print(f"Config: B=8, H=32, d=128, dtype=BF16, BLOCK_N=128")
print("=" * 75)
print(f"{'KV Len':>8} | {'Naive (ms)':>12} | {'FlashDec (ms)':>14} | {'Speedup':>8} | {'GPU Blocks':>11}")
print("-" * 75)

B, H, d = 8, 32, 128
for N in [4096, 8192, 16384, 32768, 65536]:
    Q_dec = torch.randn(B, H, 1, d, device='cuda', dtype=torch.bfloat16)
    K_dec = torch.randn(B, H, N, d, device='cuda', dtype=torch.bfloat16)
    V_dec = torch.randn(B, H, N, d, device='cuda', dtype=torch.bfloat16)

    num_splits = min(16, max(4, N // 512))
    gpu_blocks = B * H * num_splits

    try:
        t_naive = benchmark_fn(naive_attention, Q_dec, K_dec, V_dec)
        t_fd = benchmark_fn(flash_decoding_triton, Q_dec, K_dec, V_dec, num_splits)
        speedup = t_naive / t_fd
        print(f"{N:>8} | {t_naive:>12.3f} | {t_fd:>14.3f} | {speedup:>7.2f}x | {gpu_blocks:>5} / 108")
    except RuntimeError as e:
        print(f"{N:>8} | Error: {str(e)[:50]}")
    finally:
        del Q_dec, K_dec, V_dec
        torch.cuda.empty_cache()

print("=" * 75)
print("Note: Flash Decoding shines with large batches + long contexts where naive wastes GPU SMs")


FLASH DECODING BENCHMARK (Decode Phase, q_len=1)
Config: B=8, H=32, d=128, dtype=BF16, BLOCK_N=128
  KV Len |   Naive (ms) |  FlashDec (ms) |  Speedup |  GPU Blocks
---------------------------------------------------------------------------
    4096 |        0.370 |          0.349 |    1.06x |  2048 / 108
    8192 |        0.720 |          0.681 |    1.06x |  4096 / 108
   16384 |        1.399 |          1.256 |    1.11x |  4096 / 108
   32768 |        2.594 |          2.501 |    1.04x |  4096 / 108
   65536 |        5.173 |          4.955 |    1.04x |  4096 / 108
Note: Flash Decoding shines with large batches + long contexts where naive wastes GPU SMs


In [ ]:

!pip install -q bitsandbytes transformers accelerate
import torch
import time
import gc
import math
from transformers import AutoModelForCausalLM, AutoTokenizer, BitsAndBytesConfig
MODEL_NAME = "mistralai/Mistral-7B-Instruct-v0.2"

def clear_gpu():
    gc.collect()
    torch.cuda.empty_cache()
    torch.cuda.reset_peak_memory_stats()

def compute_perplexity(model, tokenizer, text, device="cuda"):
    encodings = tokenizer(text, return_tensors="pt", truncation=True, max_length=512)
    input_ids = encodings.input_ids.to(device)
    with torch.no_grad():
        outputs = model(input_ids, labels=input_ids)
    return math.exp(outputs.loss.item())

def benchmark_generation(model, tokenizer, prompts, max_tokens=128):
    total_tokens = 0
    torch.cuda.synchronize()
    start = time.perf_counter()
    for prompt in prompts:
        inputs = tokenizer(prompt, return_tensors="pt").to("cuda")
        with torch.no_grad():
            output = model.generate(
                **inputs, max_new_tokens=max_tokens,
                do_sample=False, pad_token_id=tokenizer.pad_token_id,
            )
        total_tokens += output.shape[1] - inputs.input_ids.shape[1]
    torch.cuda.synchronize()
    elapsed = time.perf_counter() - start
    return total_tokens / elapsed, total_tokens, elapsed

BENCH_PROMPTS = [
    "Explain the concept of attention in transformers:",
    "The key bottleneck in LLM inference is",
    "Write a brief overview of GPU memory optimization:",
    "Compare CUDA cores and Tensor Cores:",
]

PERPLEXITY_TEXT = (
    "The transformer architecture has revolutionized natural language processing "
    "since its introduction. Self-attention mechanisms allow the model to weigh "
    "the importance of different tokens in a sequence, enabling parallel processing "
    "of input data. The key innovation lies in the multi-head attention mechanism, "
    "which allows the model to jointly attend to information from different "
    "representation subspaces."
)

tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)
if tokenizer.pad_token is None:
    tokenizer.pad_token = tokenizer.eos_token

# -- FP16 Baseline --
print("=" * 60)
print("Loading FP16 baseline...")
print("=" * 60)
clear_gpu()
model_fp16 = AutoModelForCausalLM.from_pretrained(
    MODEL_NAME, torch_dtype=torch.float16, device_map="auto",
)
# Measure weight-only VRAM right after loading, before any inference
vram_weights_fp16 = torch.cuda.memory_allocated() / 1e9
tps_fp16, tokens_fp16, time_fp16 = benchmark_generation(model_fp16, tokenizer, BENCH_PROMPTS)
vram_peak_fp16 = torch.cuda.max_memory_allocated() / 1e9
ppl_fp16 = compute_perplexity(model_fp16, tokenizer, PERPLEXITY_TEXT)
print(f"FP16 Weights VRAM: {vram_weights_fp16:.2f} GB | Peak VRAM: {vram_peak_fp16:.2f} GB")
print(f"FP16 Throughput: {tps_fp16:.1f} tok/s | Perplexity: {ppl_fp16:.2f}")
del model_fp16
clear_gpu()

# -- NF4 4-bit --
print("\n" + "=" * 60)
print("Loading NF4 4-bit (bitsandbytes)...")
print("=" * 60)
clear_gpu()
bnb_config = BitsAndBytesConfig(
    load_in_4bit=True, bnb_4bit_quant_type="nf4", bnb_4bit_compute_dtype=torch.float16,
)
model_nf4 = AutoModelForCausalLM.from_pretrained(
    MODEL_NAME, quantization_config=bnb_config, device_map="auto",
)
vram_weights_nf4 = torch.cuda.memory_allocated() / 1e9
tps_nf4, tokens_nf4, time_nf4 = benchmark_generation(model_nf4, tokenizer, BENCH_PROMPTS)
vram_peak_nf4 = torch.cuda.max_memory_allocated() / 1e9
ppl_nf4 = compute_perplexity(model_nf4, tokenizer, PERPLEXITY_TEXT)
print(f"NF4 Weights VRAM: {vram_weights_nf4:.2f} GB | Peak VRAM: {vram_peak_nf4:.2f} GB")
print(f"NF4 Throughput: {tps_nf4:.1f} tok/s | Perplexity: {ppl_nf4:.2f}")
del model_nf4
clear_gpu()

# -- Summary --
print("\n" + "=" * 80)
print("QUANTIZATION COMPARISON -- Mistral-7B on A100")
print("=" * 80)
print(f"{'Method':>20} | {'Weights (GB)':>12} | {'Peak (GB)':>10} | {'Reduction':>10} | {'Tok/s':>8} | {'Perplexity':>10}")
print("-" * 80)
print(f"{'FP16 (baseline)':>20} | {vram_weights_fp16:>12.2f} | {vram_peak_fp16:>10.2f} | {'1.00x':>10} | {tps_fp16:>8.1f} | {ppl_fp16:>10.2f}")
print(f"{'NF4 (4-bit)':>20} | {vram_weights_nf4:>12.2f} | {vram_peak_nf4:>10.2f} | {vram_weights_fp16/vram_weights_nf4:>9.1f}x | {tps_nf4:>8.1f} | {ppl_nf4:>10.2f}")
print("=" * 80)
print(f"\nWeight compression: {vram_weights_fp16:.1f} GB -> {vram_weights_nf4:.1f} GB ({vram_weights_fp16/vram_weights_nf4:.1f}x)")
print(f"Perplexity delta: {abs(ppl_nf4 - ppl_fp16):.2f} (lower is better)")

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 60.7/60.7 MB 44.4 MB/s eta 0:00:00


tokenizer_config.json: 0.00B [00:00, ?B/s]

tokenizer.model:   0%|          | 0.00/493k [00:00<?, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/414 [00:00<?, ?B/s]

Loading FP16 baseline...


config.json:   0%|          | 0.00/596 [00:00<?, ?B/s]

`torch_dtype` is deprecated! Use `dtype` instead!


model.safetensors.index.json: 0.00B [00:00, ?B/s]

Fetching 3 files:   0%|          | 0/3 [00:00<?, ?it/s]

model-00003-of-00003.safetensors:   0%|          | 0.00/4.54G [00:00<?, ?B/s]

model-00002-of-00003.safetensors:   0%|          | 0.00/5.00G [00:00<?, ?B/s]

model-00001-of-00003.safetensors:   0%|          | 0.00/4.94G [00:00<?, ?B/s]

Loading checkpoint shards:   0%|          | 0/3 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/111 [00:00<?, ?B/s]

FP16 Weights VRAM: 14.83 GB | Peak VRAM: 14.86 GB
FP16 Throughput: 25.3 tok/s | Perplexity: 5.24

Loading NF4 4-bit (bitsandbytes)...


Loading checkpoint shards:   0%|          | 0/3 [00:00<?, ?it/s]

NF4 Weights VRAM: 4.81 GB | Peak VRAM: 7.26 GB
NF4 Throughput: 18.9 tok/s | Perplexity: 5.39

QUANTIZATION COMPARISON -- Mistral-7B on A100
              Method | Weights (GB) |  Peak (GB) |  Reduction |    Tok/s | Perplexity
--------------------------------------------------------------------------------
     FP16 (baseline) |        14.83 |      14.86 |      1.00x |     25.3 |       5.24
         NF4 (4-bit) |         4.81 |       7.26 |       3.1x |     18.9 |       5.39

Weight compression: 14.8 GB -> 4.8 GB (3.1x)
Perplexity delta: 0.15 (lower is better)


## 7. vLLM Integration — Mistral-7B on A100

vLLM combines ALL the above optimizations. On A100 (40/80GB) we can run the **full Mistral-7B** — the same model used in the original CUDA project!

| Setting | T4 (16GB) | A100 40GB | A100 80GB |
|---|---|---|---|
| Model | OPT-1.3B | Mistral-7B | Mistral-7B |
| Max seq len | 1024 | 8192 | 32768 |
| Batch size | ~4 | ~32 | ~64 |
| Throughput | ~200 tok/s | ~1500 tok/s | ~2500 tok/s |

In [ ]:
from vllm import LLM, SamplingParams

# A100 can run the full Mistral-7B (same as the original CUDA project)
gpu_mem_gb = torch.cuda.get_device_properties(0).total_memory / 1e9

if gpu_mem_gb >= 70:
    MODEL_NAME = "mistralai/Mistral-7B-Instruct-v0.2"
    MAX_MODEL_LEN = 16384
    GPU_UTIL = 0.90
    print("A100 80GB -> Mistral-7B with 16K context")
elif gpu_mem_gb >= 35:
    MODEL_NAME = "mistralai/Mistral-7B-Instruct-v0.2"
    MAX_MODEL_LEN = 8192
    GPU_UTIL = 0.90
    print("A100 40GB -> Mistral-7B with 8K context")
else:
    MODEL_NAME = "facebook/opt-1.3b"
    MAX_MODEL_LEN = 2048
    GPU_UTIL = 0.80
    print(f"Only {gpu_mem_gb:.0f}GB VRAM -> falling back to OPT-1.3B")

print(f"\nLoading {MODEL_NAME}...")
print("Internally uses: PagedAttention + Flash kernels + continuous batching")

llm = LLM(
    model=MODEL_NAME,
    dtype="bfloat16",
    gpu_memory_utilization=GPU_UTIL,
    max_model_len=MAX_MODEL_LEN,
    tensor_parallel_size=1,
    enforce_eager=False,
)
print("Model loaded!")

A100 80GB -> Mistral-7B with 16K context

Loading mistralai/Mistral-7B-Instruct-v0.2...
Internally uses: PagedAttention + Flash kernels + continuous batching
INFO 03-28 19:02:16 [utils.py:233] non-default args: {'dtype': 'bfloat16', 'max_model_len': 16384, 'disable_log_stats': True, 'model': 'mistralai/Mistral-7B-Instruct-v0.2'}
INFO 03-28 19:02:38 [model.py:533] Resolved architecture: MistralForCausalLM
INFO 03-28 19:02:38 [model.py:1582] Using max model len 16384
INFO 03-28 19:02:38 [scheduler.py:231] Chunked prefill is enabled with max_num_batched_tokens=8192.
INFO 03-28 19:02:38 [vllm.py:754] Asynchronous scheduling is enabled.
WARNING 03-28 19:02:39 [system_utils.py:152] We must use the `spawn` multiprocessing start method. Overriding VLLM_WORKER_MULTIPROC_METHOD to 'spawn'. See https://docs.vllm.ai/en/latest/usage/troubleshooting.html#python-multiprocessing for more information. Reasons: CUDA is initialized
INFO 03-28 19:03:49 [llm.py:391] Supported tasks: ['generate']
Model load

In [ ]:
sampling_params = SamplingParams(
    temperature=0.7,
    top_p=0.9,
    max_tokens=256,
)

prompts = [
    "Explain Flash Attention in simple terms:",
    "The key bottleneck in LLM inference is",
    "PagedAttention works like virtual memory because",
    "To optimize GPU utilization during text generation,",
]

print(f"Generating {len(prompts)} prompts with vLLM on A100...\n")
start = time.perf_counter()
outputs = llm.generate(prompts, sampling_params)
elapsed = time.perf_counter() - start

total_tokens = 0
for output in outputs:
    generated = output.outputs[0].text
    num_tokens = len(output.outputs[0].token_ids)
    total_tokens += num_tokens
    print(f"Prompt: {output.prompt}")
    print(f"Output ({num_tokens} tokens): {generated[:300]}")
    print()

throughput = total_tokens / elapsed
print(f"{'='*60}")
print(f"Total: {total_tokens} tokens in {elapsed:.2f}s")
print(f"Throughput: {throughput:.1f} tokens/s")
print(f"GPU: {torch.cuda.get_device_name(0)}")
print(f"VRAM used: {torch.cuda.max_memory_allocated()/1e9:.1f} GB")

Generating 4 prompts with vLLM on A100...



Rendering prompts:   0%|          | 0/4 [00:00<?, ?it/s]

Processed prompts:   0%|          | 0/4 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Prompt: Explain Flash Attention in simple terms:
Output (148 tokens): 

Flash Attention is a concept in machine learning that helps models focus on the most relevant parts of an input when processing it. It's like giving a model a pair of binoculars to zoom in on specific details instead of making it try to process everything at once. This can lead to more accurate an

Prompt: The key bottleneck in LLM inference is
Output (256 tokens):  the number of queries to the model. This number can be reduced by using the concept of contextualized embeddings, which is the idea of learning embeddings for a specific context, such as a sentence or a paragraph, rather than a single word. This can be achieved through techniques like Sentence-BERT

Prompt: PagedAttention works like virtual memory because
Output (256 tokens):  it uses a LRU (Least Recently Used) algorithm to manage which pages are loaded and which can be unloaded from memory. However, PagedAttention does not use a disk to store the unlo

In [ ]:
# Throughput stress test — batch of 16 prompts
print("\nThroughput stress test (batch=16, max_tokens=512)...\n")

stress_params = SamplingParams(temperature=0.8, top_p=0.95, max_tokens=512)
stress_prompts = [f"Write a detailed paragraph about topic {i}:" for i in range(16)]

start = time.perf_counter()
stress_outputs = llm.generate(stress_prompts, stress_params)
elapsed = time.perf_counter() - start

total_tokens = sum(len(o.outputs[0].token_ids) for o in stress_outputs)
throughput = total_tokens / elapsed

print(f"Generated {total_tokens} tokens across {len(stress_prompts)} prompts")
print(f"Time: {elapsed:.2f}s")
print(f"Throughput: {throughput:.1f} tokens/s")
print(f"Per-request latency: {elapsed/len(stress_prompts)*1000:.0f} ms")
print(f"Peak VRAM: {torch.cuda.max_memory_allocated()/1e9:.1f} GB")


Throughput stress test (batch=16, max_tokens=512)...



Rendering prompts:   0%|          | 0/16 [00:00<?, ?it/s]

Processed prompts:   0%|          | 0/16 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Generated 6539 tokens across 16 prompts
Time: 12.33s
Throughput: 530.4 tokens/s
Per-request latency: 771 ms
Peak VRAM: 0.3 GB


## Summary — A100 vs T4/L4

| Feature | T4/L4 Config | A100 Config | Why |
|---|---|---|---|
| **Tile Size** | BLOCK=64 | BLOCK=128 | 192KB SRAM/SM (2x) |
| **Precision** | FP16 | BF16 | Better range, same speed |
| **Flash Decoding Splits** | 8 | 16-32 | 108 SMs to saturate |
| **Max Seq Length** | 2048 | 16384-32768 | 40-80GB HBM2e |
| **Model** | OPT-1.3B | Mistral-7B | Full 7B fits in memory |
| **Throughput** | ~200 tok/s | ~1500+ tok/s | All factors combined |

### Key Takeaways
1. **A100's 192KB SRAM/SM** enables 128x128 tiles (4x more data per tile than 64x64)
2. **108 SMs** need more thread blocks — Flash Decoding with 16+ splits keeps them busy
3. **BF16** on A100 gives better numerical stability vs FP16 at the same performance
4. **80GB HBM2e** lets you run Mistral-7B with 32K context — impossible on T4/L4
5. **Triton auto-tunes** for A100's sm_80 architecture — we just set the right block sizes